site_name: LogicTraffic
site_description: Dokumentation für das LogicTraffic-Projekt
site_author: Salome Gwendolin Guldener
repo_name: logictraffic
repo_url: https://github.com/salomegolden/logictraffic
site_url: https://salomegolden.github.io/logictraffic/
docs_dir: docs
edit_uri: edit/main/docs/
extra_css: 
    - stylesheets/callouts.css

theme:
  name: material
  language: de
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
  icon:
    admonition:
      note: octicons/compose-24
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/light-bulb-24
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    
edit_uri: edit/main/docs/


nav:
  - Home: index.md
  - Überblick: overview.md
  - Zur Sache: 
      - topic.md
      - Darstellungswechsel: topic/darstellungswechsel.md
      - Normalformeln: topic/normalformeln.md
      - Wahrheitstabellen: topic/wahrheitstabellen.md
  - Lehrplan und Lernziele: goals.md
  - Unterrichtsplanung: lessons.md
  - Downloads: downloads.md
  - Beispiele aus dem Unterricht: examples.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:  
      inline_wrap: ['$', '$']
      block_wrap: ['$$', '$$']
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

