site_name: LogicTraffic
site_description: Dokumentation für das LogicTraffic-Projekt
site_author: Dein Name
repo_name: logictraffic
repo_url: https://github.com/salomegolden/logictraffic
site_url: https://salomegolden.github.io/logictraffic/
docs_dir: docs

theme:
  name: material
  language: de
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: docs/index.md
  - Überblick: docs/overview.md
  - Zur Sache: docs/topic.md
  - Lehrplan und Lernziele: docs/goals.md
  - Unterrichtsplanung: docs/lessons.md
  - Downloads: docs/downloads.md
  - Beispiele aus dem Unterricht: docs/examples.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list


